from .subtitle_prompts import (
    INTENT_DETECTION_PROMPT,
    SUBTITLE_GENERATION_PROMPT,
    STYLE_MODIFICATION_PROMPT,
    CONTENT_MODIFICATION_PROMPT
)

__all__ = [
    "INTENT_DETECTION_PROMPT",
    "SUBTITLE_GENERATION_PROMPT",
    "STYLE_MODIFICATION_PROMPT",
    "CONTENT_MODIFICATION_PROMPT"
]